[build]
  command = "vite build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
